# Generated by Django 5.2.8 on 2025-12-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_user_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
